##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

metadata:
  #Provide the namespace for organization's peer
  #Eg. namespace: org1-example-com
  namespace: org1-example-com
  images:
    #Provide the valid image name and version for fabric tools
    #Eg. fabric-tools: hyperledger/fabrictools:1.4.0
    fabrictools: hyperledger/fabric-tools:2.2.2
    #Provide the valid image name and version to read certificates from vault server
    #Eg.alpineutils: ghcr.io/hyperledger/bevel-alpine:latest
    alpineutils: ghcr.io/hyperledger/bevel-alpine:latest
  #Provide the custom labels
  #NOTE: Provide labels other than name, release name , release service, chart version , chart name , app.
  #Eg. labels:
  #      role: anchorpeer
  labels: anchorpeer

peer:
  #Provide the name of the peer as per deployment yaml.
  #Eg. name: peer0
  name: peer0
  #Provide the address of the peer which will update the channel about the anchor peer of the organization
  #Eg. address: peer0.org1-example-com:7051
  address: peer0.org1-example-com:7051
  #Provide the localmspid for organization
  #Eg. localmspid: Org1MSP
  localmspid: org1MSP
  #Provide the loglevel for organization's peer
  #Eg. loglevel: info
  loglevel: debug
  #Provide the value for tlsstatus to be true or false for organization's peer
  #Eg. tlsstatus: true
  tlsstatus: true

vault:
  #Provide the vaultrole for an organization
  #Eg. vaultrole: org1-vault-role
  role: vault-role
  #Provide the vault server address
  #Eg. vaultaddress: http://Vault-884963190.eu-west-1.elb.amazonaws.com
  address:
  #Provide the kubernetes auth backed configured in vault for an organization
  #Eg. authpath: fra-demo-hlkube-cluster-org1
  authpath: fra-demo-hlkube-cluster-org1
  #Provide the value for vault secretprefix
  #Eg. adminsecretprefix: secret/...
  adminsecretprefix: secret/adminsecretprefix/
  #Provide the value for vault secretprefix
  #Eg. orderersecretprefix: secret/...
  orderersecretprefix: secret/orderersecretprefix/
  #Provide the serviceaccount name for vault
  #Eg. serviceaccountname: vault-auth
  serviceaccountname: vault-auth
  #Provide the imagesecretname for vault
  #Eg. imagesecretname: regcred
  imagesecretname: ""
  #Kuberenetes secret for vault ca.cert
  #Enable or disable TLS for vault communication if value present or not
  #Eg. tls: vaultca
  tls: vaultca


channel:
  #Provide the name of the channel
  #Eg. name: mychannel
  name: mychannel

orderer:
  #Provide the address for orderer
  #Eg. address: orderer.fratest-com:7050
  address: orderer.fratest-com:7050

#Provide the base64 encoded file contents for anchorstx
anchorstx: 
