##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

#############################################################################################
# This role creates value files for storage class
#############################################################################################

# Check if StorageClass is created
- name: "Checking if the storage class {{ sc_name }} already exists"
  include_role:
    name: "{{ playbook_dir }}/../../shared/configuration/roles/check/k8_component"
  vars:
    component_type: "StorageClass"
    component_name: "{{ sc_name }}"
    type: "no_retry"

- name: "Set Variable"
  set_fact:
    get_sc: "{{ result }}"

# this task creates {{ component_type }} diretory if not exists
- name: "creating {{ release_dir }}/{{ component_type }} directory"
  include_role:
    name: "{{ playbook_dir }}/../../shared/configuration/roles/check/directory"
  vars:
    path: "{{ release_dir }}/{{ component_type }}"
  when: get_sc.resources|length == 0

#############################################################################################
# This task creates the value file for creating the storage class for Orderer
- name: Create Storage Class value file for orderers
  template:
    src: "storageclass.tpl"
    dest: "{{ values_file }}"
  vars:
    values_file: "{{ release_dir }}/{{ component_type }}/{{ sc_name }}.yaml"
  when: get_sc.resources|length == 0

# Create Storageclass via helmchart
- name: Create Storageclass via helmchart
  shell: |
    KUBECONFIG={{ kubeconfig_path }} helm install {{ sc_name }} -f {{ release_dir }}/{{ component_type }}/{{ sc_name }}.yaml {{ playbook_dir }}/../../../{{ charts_dir }}/storage_class
  vars:
    kubeconfig_path: "{{ kubernetes.config_file }}"
  when: get_sc.resources|length == 0

# Check if StorageClass created
- name: "Waiting for the creation of {{ sc_name }} storage class"
  include_role:
    name: "{{ playbook_dir }}/../../shared/configuration/roles/check/k8_component"
  vars:
    component_type: "StorageClass"
    component_name: "{{ sc_name }}"
    type: "retry"
  when: get_sc.resources|length == 0
  tags:
    - notest
