##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

apiVersion: v1
appVersion: "2.0"
description: "Hyperledger Fabric: Joins the peer to the channel."
name: join_channel
version: '0.14.1'
