##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

# Fetching the prometheus URLs
- name: Fetching the prometheus URLs
  include_tasks: nested_loop.yaml
  vars:
    nodes: "{{ org.services.peers is defined | ternary(org.services.peers, org.services.validators) }}"

#Adding the prometheus chart repo
- name: Add stable chart repo
  kubernetes.core.helm_repository:
    name: stable
    repo_url: "https://prometheus-community.github.io/helm-charts"

# Install prometheus via helmchart
# This chart supports different versions of prometheus installations
- name: Deploy the Prometheus chart
  kubernetes.core.helm:
    kubeconfig: "{{ kubeconfig_path }}"
    name: "{{ name }}-prom"
    chart_ref: stable/prometheus
    chart_version: 23.0 
    release_namespace: "{{ component_ns }}"
    create_namespace: true
    values_files:
      - "{{ playbook_dir }}/../../../platforms/hyperledger-besu/configuration/build/{{name}}-prometheus.yaml"
