##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

# Initialization of prometheus targets
- name: extracting data 
  set_fact:
    targets: []

#Extracting the prometheus targets
- name: extracting the prometheus targets 
  vars:
    prom_url: "{{ node.name }}.{{ component_name }}:{{ node.metrics.port }}"
  set_fact:
    targets: "{{ targets + [prom_url] }}"
  loop: "{{ nodes }}"
  loop_control:
    loop_var: node
  when: node.metrics.enabled == true

#Updating the helm values
- name: Updating helm values config 
  template:
    src={{ playbook_dir }}/../../../platforms/hyperledger-besu/configuration/roles/create/prometheus/templates/prometheus_release.j2
    dest={{ playbook_dir }}/../../../platforms/hyperledger-besu/configuration/build/{{ name }}-prometheus.yaml
