##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

apiVersion: v1
appVersion: "2.0"
description: "Hyperledger Fabric: Generates CA Server certs."
name: generate_cacerts
version: '0.14.1'
