##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

metadata:
  #Provide the namespace for organization's peer
  #Eg. namespace: org1-example-com
  namespace: org1-net
  images:
    #Provide the valid image name and version for fabric tools
    #Eg. fabrictools: hyperledger/fabric-tools:1.4.0
    fabrictools: hyperledger/fabric-tools:2.2.2
    #Provide the valid image name and version to read certificates from vault server
    #Eg.alpineutils: ghcr.io/hyperledger/bevel-alpine:latest
    alpineutils: ghcr.io/hyperledger/bevel-alpine:latest

storage:
  #Provide the storageclassname
  class: standard
  #Provide the storagesize
  size: 512Mi

vault:
  #Provide the vaultrole for an organization
  #Eg. vaultrole: org1-vault-role
  role: org1-vault-role
  #Provide the vault server address
  #Eg. vaultaddress: http://Vault-884963190.eu-west-1.elb.amazonaws.com
  address:
  #Provide the kubernetes auth backed configured in vault for an organization
  #Eg. authpath: fra-demo-hlkube-cluster-org1
  authpath: fra-demo-hlkube-cluster-org1
  #Provide the value for vault secretprefix
  #Eg. adminsecretprefix: secret/...
  adminsecretprefix: secret/adminsecretprefix/
  #Provide the value for vault secretprefix
  #Eg. orderersecretprefix: secret/...
  orderersecretprefix: secret/orderersecretprefix/
  #Provide the serviceaccountname for vault
  #Eg. serviceaccountname: vault-auth
  serviceaccountname: vault-auth
  #Provide the imagesecretname for vault
  #Eg. imagesecretname: regcred
  imagesecretname: ""
  #Kuberenetes secret for vault ca.cert
  #Enable or disable TLS for vault communication if value present or not
  #Eg. tls: vaultca
  tls: vaultca


peer:
  #Provide the name of the peer as per deployment yaml.
  #Eg. name: peer0
  name: peer0
  #Provide the localmspid for organization
  #Eg. localmspid: Org1MSP
  localmspid: Org1MSP
  #Provide the value for tlsstatus to be true or false for organization's peer
  #Eg. tlsstatus: true
  tlsstatus: true
  #Provide the address for the peer
  #Eg: address: peer0.org1-example-com:7051
  address: peer0.peer0-net:7051

orderer:
  #Provide the address for orderer
  #Eg. address: orderer-ext.example-com:443
  address: orderer-ext.example-com:443
